<!DOCTYPE html>

<html>
  <head>
     <meta http-equiv="content-type" content="text/html; charset=utf-8" />
     <title>
       
         Ruby's Rescue Statement Can Has Value? //
       
       TRAVISO Blog
     </title>
     <meta name="author" content="Hakan Karlidag" />
     
       <meta namne="description" content="An interesting way to catch and return an exception with very little code." />
     
     <link href="http://feeds2.feedburner.com/axaq" rel="alternate" title="Hakan Karlidag" type="application/atom+xml" />

     <link rel="stylesheet" href="/blog/stylesheets/syntax.css" type="text/css" />
     <link rel="stylesheet" href="/blog/stylesheets/default.css" type="text/css" />

     
  </head>
  <body>
    <a href="http://github.com/axaq"><img style="position: absolute; top: 0; left: 0; border: 0;" src="http://s3.amazonaws.com/github/ribbons/forkme_left_orange_ff7600.png" alt="Fork me on GitHub" /></a>

    <div id="site">
      <a id="subscribe" href="http://feeds2.feedburner.com/axaq"><img src="/blog/images/rss.png" alt="Subscribe to RSS Feed" /></a>

      <div id="search_area" style="display: none">
        <label for="search" style="display: none">Search</label>
        <img src="http://www.famfamfam.com/lab/icons/silk/icons/cancel.png" alt="X"/>
        <input id="search" />
      </div>

      <h1><a href="/blog">Welcome to traviso.js blog</a></h1>

      <div class="clear"></div>

      <div id="sidebar" class="vcard">
        <h3>Me</h3>
        <dl id="contact">
          <dt>Name</dt>
          <dd><a class="fn url" href="http://twitter.com/axaq">Hakan Karlidag</a> / <span class="nickname">axaq</span></dd>

          <dt>Email</dt>
          <dd class="email"><a href="mailto:karlidag@gmail.com">karlidag@gmail.com</a></dd>
        </dl>
        <h3>And then some</h3>
        <ul id="profiles">
          <li><a href="http://twitter.com/axaq">Twitter</a></li>

          <li><a href="http://github.com/axaq">GitHub</a></li>
        </ul>

         <div class="adr">
          <span class="locality">Indianapolis</span>
          <span class="region">IN</span>
          <span class="postal-code">46220</span>

          <span class="country-name">USA</span>

         </div>
      </div>

      <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/prototype/1.6/prototype.js"></script>

      <div id="content">
        <div id="post">
  <div class="date">19 Feb 2009</div>
  <h2>Ruby's Rescue Statement Can Has Value?</h2>
  <p>I just discovered something interesting about Ruby&#8217;s exception rescuing. Check out these two example methods that differ only by exception assignment.</p>
<div class="highlight"><pre><code class="language-ruby" data-lang="ruby"><span class="k">def</span> <span class="nf">return_nil_on_error</span>
  <span class="k">begin</span>
    <span class="k">yield</span>
  <span class="k">rescue</span>
  <span class="k">end</span>
<span class="k">end</span>

<span class="k">def</span> <span class="nf">return_exception_on_error</span>
  <span class="k">begin</span>
    <span class="k">yield</span>
  <span class="k">rescue</span> <span class="o">=&gt;</span> <span class="n">err</span>
  <span class="k">end</span>
<span class="k">end</span>

<span class="nb">puts</span> <span class="n">return_nil_on_error</span> <span class="p">{</span> <span class="k">raise</span> <span class="s2">&quot;error!&quot;</span> <span class="p">}</span><span class="o">.</span><span class="n">inspect</span>
<span class="nb">puts</span> <span class="n">return_exception_on_error</span> <span class="p">{</span> <span class="k">raise</span> <span class="s2">&quot;error!&quot;</span> <span class="p">}</span><span class="o">.</span><span class="n">inspect</span></code></pre></div><p>Running the code above and this is what you will see.</p>
<div class="highlight"><pre><code class="language-ruby" data-lang="ruby"><span class="kp">nil</span>
<span class="c1">#&lt;RuntimeError: error!&gt;</span></code></pre></div><p>It&#8217;s interesting to see that Ruby treats the a rescue block as a value expression if it assigns the exception to a variable. Is there a valid use for this oddity?</p>
</div>

<div id="related">
  <h3>Related Posts</h3>
  <ul class="posts">
    
      <li><a href="/blog/2015/03/15/engine-configuration.html">Engine Configuration</a></li>
    
      <li><a href="/blog/2015/03/15/data-file-structure.html">Data File Structure</a></li>
    
      <li><a href="/blog/2015/03/15/basic-isometric-world.html">Basic Isometric World</a></li>
    
  </ul>
</div>

      </div>

      <div class="clear"></div>

    </div>

    

    <script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	  try {
	  ga('create', 'UA-60720270-1', 'auto');
	  ga('send', 'pageview');
	  } catch(err) {}
	</script>
  </body>
</html>
